### ISSUE TITLE
Can i help you?

### ISSUE THREAD

**Issue by vvthinh** [pulseshift/openui5-gulp-starter-kit#21]
I have viewed your project. OpenUser5 library you https://openui5.hana.ondemand.com/downloads/openui5-sdk-1.50.8.zip. This project has disadvantages if offline, do not use the library You can add the bundl library feature to openui5 for faster web applications. thank you!. If you do not bundle the openui5 library, the number of requests will greatly slow down the web app.thank you!

**Comment by fuchsvomwalde** [comment]
Hi, 
as mentioned in the README, you can define any UI5 library as source, a self build bundle, a CDN link (as configured at the time) or a custom build of UI5. Please see part Configuration in the README.

Hope this information is helping you.
