### ISSUE TITLE
error install ui5-lib-util 

### ISSUE THREAD

**Issue by ednx** [pulseshift/openui5-gulp-starter-kit#40]
when the npm install command is run, it would be released throws an error Command failed: / usr / local / bin / git checkout 4.0

verbose argv "/usr/local/Cellar/node/10.11.0/bin/node" "/usr/local/bin/npm" "i" "ui5-lib-util@alpha"
34 verbose node v10.11.0
35 verbose npm  v6.4.1
36 error code 1
37 error Command failed: /usr/local/bin/git checkout 4.0

**Comment by fuchsvomwalde** [comment]
Hi @ednx can you try to use yarn for installation? And do you have some details about your OS and node version.

**Comment by ednx** [comment]
I'm going to try Yarn.

OS Mac OS 10.13.1
Node v10.11.0
Npm v6.4.1

**Comment by fuchsvomwalde** [comment]
Ok we never tested with node 10, yet. Waiting on your results with yarn and if this won't run, I'll investigate to reproduce your issue.

**Comment by ednx** [comment]
Hello,

It did not work with **Node version 10**, it tried with Yarn and it did not work because a dependency was not **compatible** with Node10. Then, I tried with **Node 8.12.0** and it did not work I threw the same error, and with YARN I installed all the dependencies and compiled satisfactorily.

Thank you
