### ISSUE TITLE
nwabap uploader integration

### ISSUE THREAD

**Issue by nimble-123** [pulseshift/openui5-gulp-starter-kit#7]
hi

the nwabap uplooader do not work for me with this integration. i am not completly into this `Promise` thing right now, but gulp keeps saying that i forgot to signal async completion of the task.

This is the terminal output i get from `yarn deploy` command.

```bash
[13:25:59] Starting 'ui5Upload'...
[13:25:59] The following tasks did not complete: deploy, ui5Upload
[13:25:59] Did you forget to signal async completion?
```

This is the corresponding source which is responsible for the error. I think it has something to do with the way ui5uploader is used here. The project itself could be composite of more than one ui5 application and therefor you want to deploy every ui5 app which is in `AppDistPath`. There is the problem i think.

Maybe the yarn command has to be more specific which app is to be deployed. So gulp does not need to iterate over all apps and instead just deploy the app specified as a option of the yarn command (`yarn deploy:<app_name_here>` something like this).

```javascript
function ui5Upload() {
.
.
.
  const mapPathToDist = sPath => sPath.replace(new RegExp(`^${SRC}`), DIST)
  const aDeployPromise = pkg.ui5.apps.map(oApp => {
    // check if nwabap config is maintained
    if (!oApp.nwabapDestination) {
      return Promise.reject(
        `Option 'nwabapDestination' config was not found for app ${oApp.name} in package.json`
      )
    }
    const sAppDistPath = mapPathToDist(oApp.path)

    return new Promise((resolve, reject) => {
      gulp
        .src([`${sAppDistPath}/**`])
        .pipe(
          ui5uploader({
            root: sAppDistPath,
            // pass conn and auth config
            ...pkg.ui5.nwabapUpload,
            // pass nwabap bsp destination
            ui5: oApp.nwabapDestination
          })
        )
        .on('error', reject)
        .on('end', resolve)
    })
  })
  return Promise.all(aDeployPromise)
}
```

**Comment by fuchsvomwalde** [comment]
Yap,

my mistake, I forgot a gulp.dest statement. In gulp 4.0 the ‚error‘ and ‚on‘ events are only called, if a gulp.dest statement was used before. So the resolve method of the promise will be executed, now. Issue should be fixed. :-)

Kind regards,
Jascha

**Comment by nimble-123** [comment]
now another error showed up :)

```bash
[14:13:04] Starting 'ui5Upload'...
[14:13:05] [FAILED] Folder /.. created.
[14:13:05] 'ui5Upload' errored after 1.65 s
[14:13:05] Error in plugin 'gulp-nwabap-ui5uploader'
Message:
    Request-Url: https://my.local.server/sap/bc/adt/filestore/ui5-bsp/objects/Z_TMP_MD/content?type=folder&isBinary=false&name=..&devclass=%24TMP&sap-language=EN
Request-Method: post
Error: got 403 response
Details:
<?xml version="1.0" encoding="utf-8"?><exc:exception xmlns:exc="http://www.sap.com/abapxml/types/communicationframework"><namespace id="com.sap.adt"/><type id="ExceptionResourceNoAccess"/><message lang="EN">Only dots or invalid combinations with dots in path segment ( path:  )</message><localizedMessage lang="EN">Only dots or invalid combinations with dots in path segment ( path:  )</localizedMessage><properties/></exc:exception>
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
[14:13:05] 'deploy' errored after 2.29 s
error Command failed with exit code 1.
```

could this be due to `.pipe(gulp.dest(DIST))` points to the wrong folder? `.pipe(gulp.dest(sAppDistPath))`

the URL in the error message from gateway server indicates that the url parameter `name` is set to `..` instead of the real folder name ùi5uploader` wants to create in the BSP container.

**Comment by fuchsvomwalde** [comment]
Oh that might be possible. Is it working with sAppDistPath?

**Comment by nimble-123** [comment]
yes just tried with `sAppDistPath` and files are all uploaded as expected :)

**Comment by fuchsvomwalde** [comment]
Fixed.
